import pw from '/root/.claude/skills/playwright-skill/node_modules/playwright-core/index.js';
import { existsSync } from 'node:fs';
const { chromium } = pw;
const exe = ['/root/.cache/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-linux64/chrome-headless-shell','/snap/bin/chromium'].find(existsSync);
const browser = await chromium.launch({ executablePath: exe, headless: true, args: ['--no-sandbox','--disable-gpu'] });
const page = await browser.newPage({ viewport: { width: 430, height: 900 } });
const errors = [];
page.on('pageerror', e=>errors.push('[pageerror] '+e.message));
page.on('console', m=>{ if(m.type()==='error') errors.push('[console] '+m.text()); });
await page.goto('http://127.0.0.1:9928/pulse', { waitUntil:'load', timeout:120000 });
await page.waitForTimeout(8000);
const item = page.locator('[data-testid^="project-"]').first();
await item.dispatchEvent('click',{bubbles:true});
await page.waitForTimeout(6000);
const body = await page.locator('body').innerText();
console.log('=== BODY 前 2000 字符 ===');
console.log(body.slice(0,2000));
console.log('=== 统计 ===');
const bashCount = (body.match(/bash/g)||[]).length;
const readCount = (body.match(/read/g)||[]).length;
const toolCall = (body.match(/tool call/g)||[]).length;
console.log('bash 出现次数:', bashCount);
console.log('read 出现次数:', readCount);
console.log('"tool call" 折叠行:', toolCall);
console.log('=== JS 错误 ===');
console.log(errors.length? errors.slice(0,5) : '无');
await browser.close();
