import pw from '/root/.claude/skills/playwright-skill/node_modules/playwright-core/index.js';
import { execSync } from 'node:child_process';
import { existsSync } from 'node:fs';
const { chromium } = pw;
const exe = ['/root/.cache/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-linux64/chrome-headless-shell','/snap/bin/chromium'].find(existsSync);
const AUTH = 'opencode:f14dd6828c5bcd6bd35d14be281c3e79802b002ddabd2bd7';
const SID = 'ses_0114cc2caffeD3ZpcCcuxcGnzR';
const browser = await chromium.launch({ executablePath: exe, headless: true, args: ['--no-sandbox','--disable-gpu'] });
const page = await browser.newPage({ viewport: { width: 430, height: 900 } });
const logs = [];
page.on('console', m => logs.push(`[${m.type()}] ${m.text().slice(0,150)}`));
page.on('pageerror', e => logs.push(`[PAGEERROR] ${e.message.slice(0,200)}`));
page.on('request', r => { if (r.url().includes('4096')) logs.push(`[REQ ${r.method()}] ${r.url().replace('http://106.13.181.13:4096','')}`); });
page.on('response', r => { if (r.url().includes('4096')) logs.push(`[RES ${r.status()}] ${r.url().replace('http://106.13.181.13:4096','')}`); });
await page.goto('http://127.0.0.1:9928/pulse', { waitUntil:'load', timeout:120000 });
await page.waitForTimeout(8000);
await page.locator('[data-testid^="project-"]').first().dispatchEvent('click', {bubbles:true});
await page.waitForTimeout(6000);
const msg = 'phone-send-test-' + Date.now().toString().slice(-6);
console.log('>>> 输入并发送:', msg);
await page.locator('input, textarea').first().fill(msg);
await page.keyboard.press('Enter');
await page.waitForTimeout(8000);
console.log('=== 4096 请求/响应 ===');
logs.filter(l => l.startsWith('[REQ') || l.startsWith('[RES')).slice(-10).forEach(l => console.log(l));
console.log('=== 页面错误 ===');
logs.filter(l => l.startsWith('[PAGEERROR') || l.startsWith('[error]')).forEach(l => console.log(l));
await page.screenshot({ path: 'test/send-repro.png' });
await browser.close();
